package api

// Code in this file is data: the complete route table, with the description
// of each endpoint attached to the endpoint itself. routes.go defines the
// shape, openapi.go turns it into a document, and server.go registers it.
func (s *Server) routes() []Route {
	return []Route{
		{
			Method: "GET", Path: "/healthz", Handler: s.handleHealth,
			Tag: "Service", Summary: "Liveness probe.",
			Detail: "Answers as soon as the process is up. It deliberately does not touch the database: a liveness probe that fails during a database blip restarts a server that was working.",
			Public: true,
			Return: "{\"status\":\"ok\"}",
		},
		{
			Method: "GET", Path: "/readyz", Handler: s.handleReady,
			Tag: "Service", Summary: "Readiness probe.",
			Detail: "Checks the database and the vault seal. A sealed or unreachable instance reports not-ready so a load balancer stops sending it work.",
			Public: true,
			Return: "{\"status\":\"ready\"} or 503",
		},
		{
			Method: "GET", Path: "/api/v1/openapi.json", Handler: s.handleOpenAPI,
			Tag: "Service", Summary: "This API as an OpenAPI 3.1 document.",
			Detail: "Unauthenticated on purpose. Documentation you have to log in to read is documentation nobody reads, and the document describes shapes, not data.",
			Public: true,
		},
		{
			Method: "GET", Path: "/api/v1/docs", Handler: s.handleAPIDocs,
			Tag: "Service", Summary: "Browsable API reference.",
			Detail: "A self-contained page rendered from the same route table the router uses, so it cannot describe an endpoint that does not exist.",
			Public: true,
		},
		{
			Method: "GET", Path: "/api/v1/status", Handler: s.handleSchedulerStatus,
			Tag: "Service", Summary: "Scheduler and worker status.",
			Detail:     "Reports whether this instance holds the scheduler leadership lock, plus queue depth by state. With several replicas, exactly one should report leader true.",
			Permission: "job.read",
		},
		{
			Method: "GET", Path: "/api/v1/connectors", Handler: s.handleListConnectors,
			Tag: "Service", Summary: "Registered connectors and their capabilities.",
			Detail:     "Capabilities are declared, not assumed. A network device that cannot list its keys says so here rather than failing at reconcile time.",
			Permission: "target.read",
		},
		{
			Method: "GET", Path: "/api/v1/dashboard", Handler: s.handleDashboard,
			Tag: "Service", Summary: "Fleet summary counts.",
			Permission: "key.read",
		},
		{
			Method: "POST", Path: "/api/v1/auth/login", Handler: s.handleLogin,
			Tag: "Authentication", Summary: "Sign in and open a session.",
			Detail: "Returns 401 with mfa_required when the account has a second factor and no code was supplied. Failed attempts count towards a time-boxed lockout. While the account's must_change_password flag is set, the session may call only /auth/me, /auth/logout and /auth/password; everything else answers 403 with password_change_required.",
			Public: true,
			Body: []Field{
				{Name: "username", Type: "string", Description: "Account name.", Required: true},
				{Name: "password", Type: "string", Description: "Account password.", Required: true},
				{Name: "totp_code", Type: "string", Description: "Six-digit code, or a recovery code."},
			},
			Return: "{token, expires_at, user, roles, permissions, mfa_verified}",
		},
		{
			Method: "POST", Path: "/api/v1/auth/logout", Handler: s.handleLogout,
			Tag: "Authentication", Summary: "Revoke the current session.",
		},
		{
			Method: "GET", Path: "/api/v1/auth/me", Handler: s.handleMe,
			Tag: "Authentication", Summary: "The signed-in account, its roles and effective permissions.",
			Detail: "permissions is the flattened effective set after role grants and per-user overrides, which is what the interface uses to decide what to show.",
		},
		{
			Method: "POST", Path: "/api/v1/auth/step-up", Handler: s.handleStepUp,
			Tag: "Authentication", Summary: "Re-verify the second factor mid-session.",
			Detail: "Sensitive operations — revealing a private key, taking a full backup — require a second factor verified recently, not merely at sign-in.",
			Body: []Field{
				{Name: "totp_code", Type: "string", Description: "Current six-digit code.", Required: true},
			},
		},
		{
			Method: "POST", Path: "/api/v1/auth/totp/enrol", Handler: s.handleTOTPEnrol,
			Tag: "Authentication", Summary: "Begin second-factor enrolment.",
			Detail: "Returns the secret, an otpauth:// URI, a scannable QR code as a data: URI, and ten single-use recovery codes. Enrolment is not active until confirmed, so abandoning this call locks nobody out. The recovery codes are shown exactly once.",
			Return: "{secret, uri, qr_code, recovery_codes}",
		},
		{
			Method: "POST", Path: "/api/v1/auth/totp/confirm", Handler: s.handleTOTPConfirm,
			Tag: "Authentication", Summary: "Complete enrolment by proving possession.",
			Body: []Field{
				{Name: "totp_code", Type: "string", Description: "Code generated from the new secret.", Required: true},
			},
		},
		{
			Method: "POST", Path: "/api/v1/auth/totp/recovery-codes", Handler: s.handleRegenerateRecoveryCodes,
			Tag: "Authentication", Summary: "Issue a fresh set of recovery codes.",
			Detail: "Invalidates the previous set. Requires a current code: without that check, anyone holding a live session could mint themselves a permanent bypass of the second factor.",
			Body: []Field{
				{Name: "totp_code", Type: "string", Description: "Current six-digit code.", Required: true},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/auth/totp", Handler: s.handleDisableTOTP,
			Tag: "Authentication", Summary: "Remove your own second factor.",
			Body: []Field{
				{Name: "totp_code", Type: "string", Description: "Current six-digit code.", Required: true},
			},
		},
		{
			Method: "POST", Path: "/api/v1/auth/password", Handler: s.handleChangeOwnPassword,
			Tag: "Authentication", Summary: "Change your own password.",
			Detail: "Requires the current password. Administrators reset other accounts through the users endpoint instead.",
			Body: []Field{
				{Name: "current_password", Type: "string", Description: "The password in use now.", Required: true},
				{Name: "password", Type: "string", Description: "The replacement, at least 12 characters.", Required: true},
			},
		},
		{
			Method: "GET", Path: "/api/v1/users", Handler: s.handleListUsers,
			Tag: "Users", Summary: "List accounts with their roles.",
			Permission: "user.read",
		},
		{
			Method: "POST", Path: "/api/v1/users", Handler: s.handleCreateUser,
			Tag: "Users", Summary: "Create an account.",
			Permission: "user.write",
			Body: []Field{
				{Name: "username", Type: "string", Description: "Lowercased and trimmed.", Required: true},
				{Name: "password", Type: "string", Description: "At least 12 characters.", Required: true},
				{Name: "email", Type: "string", Description: "Optional contact address."},
				{Name: "display_name", Type: "string", Description: "Shown in listings."},
				{Name: "roles", Type: "string[]", Description: "Role names to grant, e.g. [\"operator\"]."},
				{Name: "must_change_password", Type: "boolean", Description: "Force a change at next sign-in."},
				{Name: "active", Type: "boolean", Description: "Defaults to true."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/users/{id}", Handler: s.handleGetUser,
			Tag: "Users", Summary: "Read one account.",
			Permission: "user.read",
		},
		{
			Method: "PATCH", Path: "/api/v1/users/{id}", Handler: s.handleUpdateUser,
			Tag: "Users", Summary: "Change an account's profile, roles, or active state.",
			Detail:     "Every field is optional; omitting one leaves it alone. Refuses to deactivate or demote the last active administrator, and refuses to let you deactivate yourself.",
			Permission: "user.write",
			Body: []Field{
				{Name: "email", Type: "string", Description: "Replacement address."},
				{Name: "display_name", Type: "string", Description: "Replacement display name."},
				{Name: "active", Type: "boolean", Description: "Enable or disable sign-in."},
				{Name: "must_change_password", Type: "boolean", Description: "Force a change at next sign-in."},
				{Name: "roles", Type: "string[]", Description: "Replaces the role set outright."},
				{Name: "unlock", Type: "boolean", Description: "Clear a failed-login lockout."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/users/{id}", Handler: s.handleDeleteUser,
			Tag: "Users", Summary: "Delete an account.",
			Detail:     "Sessions, role bindings, and API tokens go with it. Audit rows do not: an audit trail that disappears with its actor is not an audit trail.",
			Permission: "user.write",
		},
		{
			Method: "POST", Path: "/api/v1/users/{id}/password", Handler: s.handleSetUserPassword,
			Tag: "Users", Summary: "Set an account's password.",
			Detail:     "An administrator does not supply the old password, which is the point of a reset; the account is flagged to change it at next sign-in. Changing your own password through this route does require the current one.",
			Permission: "user.write",
			Body: []Field{
				{Name: "password", Type: "string", Description: "The new password.", Required: true},
				{Name: "current_password", Type: "string", Description: "Required only when changing your own."},
				{Name: "must_change_password", Type: "boolean", Description: "Defaults to true for administrative resets."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/users/{id}/reset-totp", Handler: s.handleResetUserTOTP,
			Tag: "Users", Summary: "Clear an account's second factor.",
			Detail:     "The lost-phone path, and the most dangerous button in the product: it turns a two-factor account into a one-factor account. Loudly audited, and refused on your own account so a second person is always in the story.",
			Permission: "user.write",
		},
		{
			Method: "GET", Path: "/api/v1/roles", Handler: s.handleListRoles,
			Tag: "Users", Summary: "List roles and their permissions.",
			Permission: "role.read",
		},
		{
			Method: "GET", Path: "/api/v1/permissions", Handler: s.handleListPermissions,
			Tag: "Users", Summary: "The permission vocabulary this build defines.",
			Detail: "Published so a client does not have to ship a copy that drifts. Each entry carries the group it belongs to.",
		},
		{
			Method: "GET", Path: "/api/v1/api-tokens", Handler: s.handleListTokens,
			Tag: "API tokens", Summary: "List tokens with their status.",
			Permission: "api_token.read",
		},
		{
			Method: "POST", Path: "/api/v1/api-tokens", Handler: s.handleCreateToken,
			Tag: "API tokens", Summary: "Mint a token; the secret is returned once.",
			Detail:     "A token can never exceed the rights of the account behind it, and asking for more is rejected rather than silently trimmed. Tokens carry no second factor, so reveal and other step-up routes stay closed to them — deliberate: step-up exists so a human confirms in the moment, and a CI variable confirms nothing.",
			Permission: "api_token.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "How this token will be recognised later.", Required: true},
				{Name: "permissions", Type: "string[]", Description: "Narrow the token below its owner's rights. Empty inherits everything the owner holds."},
				{Name: "scopes", Type: "string[]", Description: "Restrict to resources carrying these tags."},
				{Name: "expires_in", Type: "string", Description: "A Go duration such as 720h. Omit for no expiry."},
				{Name: "user_id", Type: "string", Description: "Mint on behalf of another account; needs user.write."},
			},
			Return: "{token, secret, notice}",
		},
		{
			Method: "POST", Path: "/api/v1/api-tokens/{id}/revoke", Handler: s.handleRevokeToken,
			Tag: "API tokens", Summary: "Stop a token working, keeping its history.",
			Permission: "api_token.write",
		},
		{
			Method: "DELETE", Path: "/api/v1/api-tokens/{id}", Handler: s.handleDeleteToken,
			Tag: "API tokens", Summary: "Delete a token record outright.",
			Permission: "api_token.write",
		},
		{
			Method: "GET", Path: "/api/v1/keys", Handler: s.handleListKeys,
			Tag: "Keys", Summary: "List managed keys.",
			Permission: "key.read",
			Query: []Param{
				{Name: "status", Type: "string", Description: "Filter by lifecycle status.", Repeatable: true},
				{Name: "class", Type: "string", Description: "Filter by key class.", Repeatable: true},
				{Name: "tag", Type: "string", Description: "Filter by tag.", Repeatable: true},
				{Name: "q", Type: "string", Description: "Substring match on name or comment."},
				{Name: "limit", Type: "integer", Description: "Page size."},
				{Name: "offset", Type: "integer", Description: "Page offset."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/keys", Handler: s.handleCreateKey,
			Tag: "Keys", Summary: "Generate a keypair.",
			Detail:     "SKM holds the private half encrypted. That is what makes unattended rotation possible, and it is why the reveal route is gated the way it is.",
			Permission: "key.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "Unique within the install.", Required: true},
				{Name: "algorithm", Type: "string", Description: "ed25519, ecdsa-p256/384/521, or rsa-3072/4096."},
				{Name: "comment", Type: "string", Description: "Trailing comment on the public key line."},
				{Name: "description", Type: "string", Description: "Free text."},
				{Name: "tags", Type: "string[]", Description: "Used for scoping and selectors."},
				{Name: "key_class", Type: "string", Description: "standard or break_glass."},
				{Name: "valid_days", Type: "integer", Description: "Days until the key expires. 0 for no expiry."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/keys/import", Handler: s.handleImportKey,
			Tag: "Keys", Summary: "Import an existing private key.",
			Permission: "key.import",
			Body: []Field{
				{Name: "name", Type: "string", Description: "Unique within the install.", Required: true},
				{Name: "private_key", Type: "string", Description: "PEM or OpenSSH private key.", Required: true},
				{Name: "passphrase", Type: "string", Description: "Required if the key is encrypted."},
				{Name: "tags", Type: "string[]", Description: "Used for scoping and selectors."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/keys/{id}", Handler: s.handleGetKey,
			Tag: "Keys", Summary: "Read one key. Never includes private material.",
			Permission: "key.read",
		},
		{
			Method: "PATCH", Path: "/api/v1/keys/{id}", Handler: s.handleUpdateKey,
			Tag: "Keys", Summary: "Rename, retag, or re-date a key.",
			Permission: "key.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "Replacement name."},
				{Name: "description", Type: "string", Description: "Replacement description."},
				{Name: "tags", Type: "string[]", Description: "Replaces the tag set."},
				{Name: "expires_at", Type: "string", Description: "RFC 3339 timestamp, or null to clear."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/keys/{id}", Handler: s.handleDeleteKey,
			Tag: "Keys", Summary: "Delete a key and shred its private half.",
			Detail:     "Irreversible in the strongest sense the product offers. Refused while any assignment still points at the key: revoke, retire the deployments, then delete.",
			Permission: "key.delete",
		},
		{
			Method: "POST", Path: "/api/v1/keys/{id}/reveal", Handler: s.handleRevealKey,
			Tag: "Keys", Summary: "Return the private key.",
			Detail:     "The only route that emits private material. Requires a recent second factor and writes a loud audit entry naming the reason. Break-glass keys need a separate permission again.",
			Permission: "key.reveal",
			StepUp:     true,
			Body: []Field{
				{Name: "reason", Type: "string", Description: "Recorded in the audit entry.", Required: true},
			},
		},
		{
			Method: "POST", Path: "/api/v1/keys/{id}/revoke", Handler: s.handleRevokeKey,
			Tag: "Keys", Summary: "Mark a key revoked or compromised.",
			Permission: "key.revoke",
			Body: []Field{
				{Name: "compromised", Type: "boolean", Description: "Marks compromised rather than merely revoked."},
				{Name: "reason", Type: "string", Description: "Recorded in the audit entry."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/keys/{id}/status", Handler: s.handleSetKeyStatus,
			Tag: "Keys", Summary: "Move a key to another lifecycle status.",
			Permission: "key.write",
			Body: []Field{
				{Name: "status", Type: "string", Description: "pending, staged, active, retiring, retired, revoked, compromised.", Required: true},
			},
		},
		{
			Method: "GET", Path: "/api/v1/targets", Handler: s.handleListTargets,
			Tag: "Targets", Summary: "List targets.",
			Permission: "target.read",
			Query: []Param{
				{Name: "kind", Type: "string", Description: "Filter by kind.", Repeatable: true},
				{Name: "connector", Type: "string", Description: "Filter by connector.", Repeatable: true},
				{Name: "tag", Type: "string", Description: "Filter by tag.", Repeatable: true},
				{Name: "health", Type: "string", Description: "Filter by health.", Repeatable: true},
				{Name: "q", Type: "string", Description: "Substring match on name or address."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/targets", Handler: s.handleCreateTarget,
			Tag: "Targets", Summary: "Register a target.",
			Permission: "target.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "Unique within the install.", Required: true},
				{Name: "address", Type: "string", Description: "Hostname or IP.", Required: true},
				{Name: "kind", Type: "string", Description: "linux, netdev, git, exec, and so on."},
				{Name: "connector", Type: "string", Description: "Defaults to kind."},
				{Name: "port", Type: "integer", Description: "Defaults to the connector's port."},
				{Name: "config", Type: "object", Description: "Connector-specific settings, such as a netdev profile."},
				{Name: "credential_id", Type: "string", Description: "Credential used to reach it."},
				{Name: "tags", Type: "string[]", Description: "Used for scoping and selectors."},
				{Name: "is_canary", Type: "boolean", Description: "Rotations reach canaries in the first wave."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/targets/{id}", Handler: s.handleGetTarget,
			Tag: "Targets", Summary: "Read one target.",
			Permission: "target.read",
		},
		{
			Method: "PATCH", Path: "/api/v1/targets/{id}", Handler: s.handleUpdateTarget,
			Tag: "Targets", Summary: "Change a target in place.",
			Detail:     "Every field is optional; omitting one leaves it alone. Renaming or correcting a port no longer means deleting the row and losing its assignments and history along with the typo.",
			Permission: "target.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "Replacement name."},
				{Name: "address", Type: "string", Description: "Replacement address."},
				{Name: "port", Type: "integer", Description: "Replacement port."},
				{Name: "connector", Type: "string", Description: "Must be a registered connector."},
				{Name: "kind", Type: "string", Description: "Replacement kind."},
				{Name: "config", Type: "object", Description: "Replaces the config object."},
				{Name: "credential_id", Type: "string", Description: "Bind a different credential."},
				{Name: "clear_credential", Type: "boolean", Description: "Unbind the credential."},
				{Name: "tags", Type: "string[]", Description: "Replaces the tag set."},
				{Name: "enabled", Type: "boolean", Description: "Include or exclude from automation."},
				{Name: "is_canary", Type: "boolean", Description: "Mark as a canary."},
				{Name: "reconcile_mode", Type: "string", Description: "report_only, auto_heal, or disabled."},
				{Name: "clear_host_key_pin", Type: "boolean", Description: "Forget the pinned host key so the next connection re-pins. Separate from the rest because clearing it means trusting a host key you have not seen before."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/targets/{id}", Handler: s.handleDeleteTarget,
			Tag: "Targets", Summary: "Delete a target.",
			Detail:     "Removes SKM's record. Keys already installed on the host are not touched, which is worth knowing before treating this as a way to withdraw access.",
			Permission: "target.delete",
		},
		{
			Method: "POST", Path: "/api/v1/targets/{id}/probe", Handler: s.handleProbeTarget,
			Tag: "Targets", Summary: "Test reachability and pin the host key.",
			Detail:     "First contact records the host key. A later mismatch aborts rather than trusting it, so a probe is also how you adopt a host key deliberately.",
			Permission: "target.read",
		},
		{
			Method: "GET", Path: "/api/v1/targets/{id}/principals", Handler: s.handleListPrincipals,
			Tag: "Targets", Summary: "List the logins managed on a target.",
			Permission: "target.read",
		},
		{
			Method: "POST", Path: "/api/v1/targets/{id}/principals", Handler: s.handleCreatePrincipal,
			Tag: "Targets", Summary: "Manage another login on a target.",
			Permission: "target.write",
			Body: []Field{
				{Name: "username", Type: "string", Description: "The account keys are installed for.", Required: true},
				{Name: "authorized_keys_path", Type: "string", Description: "Override the connector's default path."},
				{Name: "use_sudo", Type: "boolean", Description: "Write as another user through sudo."},
			},
		},
		{
			Method: "PATCH", Path: "/api/v1/targets/{id}/principals/{principalId}", Handler: s.handleUpdatePrincipal,
			Tag: "Targets", Summary: "Change a managed login.",
			Permission: "target.write",
			Body: []Field{
				{Name: "username", Type: "string", Description: "Replacement username."},
				{Name: "authorized_keys_path", Type: "string", Description: "Replacement path."},
				{Name: "use_sudo", Type: "boolean", Description: "Write through sudo."},
				{Name: "enabled", Type: "boolean", Description: "Include in automation."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/targets/{id}/principals/{principalId}", Handler: s.handleDeletePrincipal,
			Tag: "Targets", Summary: "Stop managing a login.",
			Detail:     "Stops tracking. Keys already on the host stay there — the response says so, because the difference between 'stopped tracking' and 'access withdrawn' is the kind of thing that gets assumed wrongly.",
			Permission: "target.write",
		},
		{
			Method: "GET", Path: "/api/v1/targets/{id}/snapshots", Handler: s.handleListSnapshots,
			Tag: "Targets", Summary: "Pre-mutation snapshots for a target.",
			Permission: "target.read",
		},
		{
			Method: "GET", Path: "/api/v1/targets/{id}/authorized-keys/{username}", Handler: s.handleAuthorizedKeys,
			Tag: "Targets", Summary: "The authorized_keys content SKM intends for a login.",
			Detail:     "Desired state, rendered. Useful for a configuration management system that would rather write the file itself.",
			Permission: "target.read",
		},
		{
			Method: "GET", Path: "/api/v1/credentials", Handler: s.handleListCredentials,
			Tag: "Targets", Summary: "List credentials. Secrets are never returned.",
			Permission: "credential.read",
		},
		{
			Method: "POST", Path: "/api/v1/credentials", Handler: s.handleCreateCredential,
			Tag: "Targets", Summary: "Store a credential.",
			Permission: "credential.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "How it is referred to.", Required: true},
				{Name: "kind", Type: "string", Description: "ssh_password, ssh_key, or api_token.", Required: true},
				{Name: "secret", Type: "string", Description: "Sealed immediately; never returned.", Required: true},
				{Name: "username", Type: "string", Description: "Login name to authenticate as."},
				{Name: "key_id", Type: "string", Description: "Use a managed key as the credential instead of a pasted secret."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/credentials/{id}", Handler: s.handleDeleteCredential,
			Tag: "Targets", Summary: "Delete a credential.",
			Detail:     "Refused while a target still refers to it, and the refusal names the targets rather than returning a constraint violation.",
			Permission: "credential.write",
		},
		{
			Method: "GET", Path: "/api/v1/assignments", Handler: s.handleListAssignments,
			Tag: "Deployment", Summary: "List desired-state assignments.",
			Permission: "key.read",
			Query: []Param{
				{Name: "key_id", Type: "string", Description: "Filter to one key."},
				{Name: "target_id", Type: "string", Description: "Filter to one target."},
				{Name: "state", Type: "string", Description: "Filter by deployment state.", Repeatable: true},
			},
		},
		{
			Method: "POST", Path: "/api/v1/assignments", Handler: s.handleCreateAssignment,
			Tag: "Deployment", Summary: "Assign a key to a login.",
			Detail:     "Records intent. Nothing reaches the host until a deploy runs, which is what makes the desired-state diff meaningful.",
			Permission: "key.write",
			Body: []Field{
				{Name: "key_id", Type: "string", Description: "Key to install.", Required: true},
				{Name: "target_id", Type: "string", Description: "Target to install it on.", Required: true},
				{Name: "principal_id", Type: "string", Description: "Login to install it for.", Required: true},
				{Name: "options", Type: "object", Description: "authorized_keys options such as from, command, no-pty."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/assignments/{id}", Handler: s.handleDeleteAssignment,
			Tag: "Deployment", Summary: "Remove an assignment.",
			Permission: "key.write",
		},
		{
			Method: "POST", Path: "/api/v1/deploy", Handler: s.handleDeploy,
			Tag: "Deployment", Summary: "Apply desired state to one login on one target.",
			Detail: "dry_run renders the diff without touching anything, and is the honest " +
				"default for a first run. Every mutation snapshots the file first, and the " +
				"engine refuses to remove the last working key from a target. " +
				"Converging a whole host means one call per managed login: the unit is a " +
				"principal because that is the unit a snapshot and a rollback cover.",
			Permission: "deploy.execute",
			Body: []Field{
				{Name: "target_id", Type: "string", Description: "Target to converge.", Required: true},
				{Name: "principal_id", Type: "string", Description: "Which managed login on it.", Required: true},
				{Name: "dry_run", Type: "boolean", Description: "Render the diff and stop."},
				{Name: "prune", Type: "boolean", Description: "Remove managed keys that are no longer assigned. Off by default, so a deployment only ever adds."},
				{Name: "verify_auth", Type: "boolean", Description: "Open a fresh connection with each deployed key to prove it authenticates, rather than trusting that the file was written."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/rollback/{snapshotId}", Handler: s.handleRollback,
			Tag: "Deployment", Summary: "Restore a login's keys from a snapshot.",
			Detail:     "Writes back the exact bytes captured before the change and verifies the checksum.",
			Permission: "changeset.rollback",
		},
		{
			Method: "GET", Path: "/api/v1/rotations", Handler: s.handleListRotations,
			Tag: "Rotation", Summary: "List rotations.",
			Permission: "rotation.read",
			Query: []Param{
				{Name: "state", Type: "string", Description: "Filter by state.", Repeatable: true},
				{Name: "limit", Type: "integer", Description: "Page size."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/rotations", Handler: s.handlePlanRotation,
			Tag: "Rotation", Summary: "Plan a rotation without starting it.",
			Detail:     "Resolves the selector to a concrete target set and renders the per-target diff. Nothing mutates until start.",
			Permission: "rotation.write",
			Body: []Field{
				{Name: "key_id", Type: "string", Description: "The key to rotate.", Required: true},
				{Name: "algorithm", Type: "string", Description: "Algorithm for the successor. Defaults to the current key's."},
				{Name: "soak_hours", Type: "integer", Description: "Hours both keys stay live before the old one is retired. 0 means no soak; omit for the default."},
				{Name: "canary_percent", Type: "integer", Description: "Share of targets in the first wave."},
				{Name: "failure_threshold", Type: "integer", Description: "Abort the wave above this many failures."},
				{Name: "approval_required", Type: "boolean", Description: "Hold at planned until approved."},
				{Name: "dry_run", Type: "boolean", Description: "Plan and render the diff without ever mutating."},
				{Name: "start", Type: "boolean", Description: "Begin immediately after planning instead of waiting for a start call."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/rotations/{id}", Handler: s.handleGetRotation,
			Tag: "Rotation", Summary: "Read a rotation and its per-target progress.",
			Permission: "rotation.read",
		},
		{
			Method: "POST", Path: "/api/v1/rotations/{id}/start", Handler: s.handleStartRotation,
			Tag: "Rotation", Summary: "Begin a planned rotation.",
			Detail:     "From here the engine drives itself through the job queue: stage, verify with a fresh connection using the new key, promote, soak, retire. Every transition is a database write, so a restart mid-rotation resumes rather than restarts.",
			Permission: "rotation.execute",
		},
		{
			Method: "POST", Path: "/api/v1/rotations/{id}/approve", Handler: s.handleApproveRotation,
			Tag: "Rotation", Summary: "Approve a rotation that requires it.",
			Permission: "rotation.approve",
		},
		{
			Method: "POST", Path: "/api/v1/rotations/{id}/abort", Handler: s.handleAbortRotation,
			Tag: "Rotation", Summary: "Stop a rotation where it stands.",
			Detail:     "Safe at any state. Keys already staged are left in place — both keys valid is the safe half of add-before-remove.",
			Permission: "rotation.abort",
			Body: []Field{
				{Name: "reason", Type: "string", Description: "Recorded against the rotation."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/rotation-policies", Handler: s.handleListPolicies,
			Tag: "Rotation", Summary: "List scheduled rotation policies.",
			Permission: "rotation.read",
		},
		{
			Method: "POST", Path: "/api/v1/rotation-policies", Handler: s.handleCreatePolicy,
			Tag: "Rotation", Summary: "Create a scheduled policy.",
			Permission: "rotation.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "How the policy is recognised.", Required: true},
				{Name: "cron_expr", Type: "string", Description: "Five-field cron expression. Preview it first with the preview endpoint."},
				{Name: "max_age_days", Type: "integer", Description: "Rotate keys older than this many days."},
				{Name: "key_tags", Type: "string[]", Description: "Cover keys carrying any of these tags."},
				{Name: "target_tags", Type: "string[]", Description: "Restrict to targets carrying any of these tags."},
				{Name: "key_class", Type: "string", Description: "Restrict to one key class."},
				{Name: "algorithm", Type: "string", Description: "Algorithm for successors."},
				{Name: "soak_hours", Type: "integer", Description: "Hours both keys stay live."},
				{Name: "canary_percent", Type: "integer", Description: "Share of targets in the first wave."},
				{Name: "failure_threshold", Type: "integer", Description: "Abort a wave above this many failures."},
				{Name: "approval_required", Type: "boolean", Description: "Hold each run until approved."},
				{Name: "enabled", Type: "boolean", Description: "Whether the schedule fires."},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/rotation-policies/{id}", Handler: s.handleDeletePolicy,
			Tag: "Rotation", Summary: "Delete a policy.",
			Permission: "rotation.write",
		},
		{
			Method: "GET", Path: "/api/v1/rotation-policies/preview", Handler: s.handlePreviewSchedule,
			Tag: "Rotation", Summary: "Next run times for a cron expression.",
			Detail:     "Answers 'when will this actually fire' before the policy is saved, which is the question a cron field always raises.",
			Permission: "rotation.read",
			Query: []Param{
				{Name: "cron", Type: "string", Description: "The expression to evaluate."},
				{Name: "count", Type: "integer", Description: "How many occurrences to return."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/jobs", Handler: s.handleListJobs,
			Tag: "Jobs", Summary: "List queued and finished jobs.",
			Permission: "job.read",
			Query: []Param{
				{Name: "state", Type: "string", Description: "Filter by state.", Repeatable: true},
				{Name: "type", Type: "string", Description: "Filter by job type.", Repeatable: true},
				{Name: "limit", Type: "integer", Description: "Page size."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/jobs/{id}", Handler: s.handleGetJob,
			Tag: "Jobs", Summary: "Read one job.",
			Permission: "job.read",
		},
		{
			Method: "GET", Path: "/api/v1/jobs/{id}/logs", Handler: s.handleJobLogs,
			Tag: "Jobs", Summary: "Progress lines for a job.",
			Detail:     "Reads forward from a cursor so following a long job does not re-fetch its whole log each poll.",
			Permission: "job.read",
			Query: []Param{
				{Name: "after", Type: "integer", Description: "Return lines after this id."},
				{Name: "limit", Type: "integer", Description: "Page size."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/jobs/{id}/cancel", Handler: s.handleCancelJob,
			Tag: "Jobs", Summary: "Cancel a queued or running job.",
			Permission: "job.cancel",
		},
		{
			Method: "POST", Path: "/api/v1/reconcile", Handler: s.handleReconcile,
			Tag: "Inventory", Summary: "Read actual state back and diff it.",
			Detail:     "Two payoffs: it heals drift where the target allows it, and it surfaces keys SKM did not deploy. For an estate that has never had key management, the second is usually the first genuinely useful thing to look at.",
			Permission: "reconcile.run",
			Body: []Field{
				{Name: "target_id", Type: "string", Description: "Scan one target. Omit to sweep the whole fleet."},
				{Name: "async", Type: "boolean", Description: "Queue the work as a job rather than waiting. A fleet sweep is slow enough to time out a request, so this is the sensible choice there."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/discovered-keys", Handler: s.handleListDiscovered,
			Tag: "Inventory", Summary: "Keys found on targets that SKM did not deploy.",
			Permission: "target.read",
			Query: []Param{
				{Name: "state", Type: "string", Description: "unmanaged, adopted, ignored, removed.", Repeatable: true},
				{Name: "target_id", Type: "string", Description: "Filter to one target."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/discovered-keys/{id}/adopt", Handler: s.handleAdoptKey,
			Tag: "Inventory", Summary: "Track a discovered key.",
			Detail:     "SKM does not hold the private half, so an adopted key can be tracked and removed but never rotated. The response says so rather than letting that be discovered later.",
			Permission: "key.adopt",
			Body: []Field{
				{Name: "name", Type: "string", Description: "Name for the adopted key."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/discovered-keys/{id}/ignore", Handler: s.handleIgnoreDiscovered,
			Tag: "Inventory", Summary: "Mark a discovered key as accounted for.",
			Permission: "target.write",
		},
		{
			Method: "GET", Path: "/api/v1/backups", Handler: s.handleListBackups,
			Tag: "Backups", Summary: "List archives.",
			Permission: "backup.read",
		},
		{
			Method: "POST", Path: "/api/v1/backups", Handler: s.handleCreateBackup,
			Tag: "Backups", Summary: "Write an encrypted archive.",
			Detail:     "Encrypted under a passphrase of its own rather than the instance master key, so it can be restored into a fresh install. The passphrase is never stored and cannot be recovered. A full archive exports every private key, so it is gated like a reveal.",
			Permission: "backup.create",
			StepUp:     true,
			Body: []Field{
				{Name: "passphrase", Type: "string", Description: "At least 12 characters.", Required: true},
				{Name: "name", Type: "string", Description: "How the archive is recognised."},
				{Name: "kind", Type: "string", Description: "full, keys_only, or metadata."},
				{Name: "retain_days", Type: "integer", Description: "0 keeps it indefinitely."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/backups/{id}/verify", Handler: s.handleVerifyBackup,
			Tag: "Backups", Summary: "Prove an archive can be restored.",
			Detail:     "Decrypts every private key and matches it against the recorded fingerprint, then discards what it read. 'The backup ran' and 'the backup can be restored' are different claims; this checks the second.",
			Permission: "backup.read",
			Body: []Field{
				{Name: "passphrase", Type: "string", Description: "The archive's passphrase.", Required: true},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/backups/{id}", Handler: s.handleDeleteBackup,
			Tag: "Backups", Summary: "Delete an archive and its file.",
			Permission: "backup.create",
		},
		{
			Method: "POST", Path: "/api/v1/restore", Handler: s.handleRestoreBackup,
			Tag: "Backups", Summary: "Restore an archive into this instance.",
			Detail:     "Keys already present are skipped, never overwritten: a restore that replaced a live key with an older copy would be a way to reintroduce a revoked one.",
			Permission: "backup.restore",
			StepUp:     true,
			Body: []Field{
				{Name: "passphrase", Type: "string", Description: "The archive's passphrase.", Required: true},
				{Name: "backup_id", Type: "string", Description: "An archive this instance knows about."},
				{Name: "path", Type: "string", Description: "A file path, for restoring into a fresh install."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/consumers", Handler: s.handleListConsumers,
			Tag: "Consumers", Summary: "List private-key sinks.",
			Detail:     "Consumers receive the private half, unlike targets which receive the public. Conflating the two is what breaks rotation: a consumer must be updated before the old key is retired.",
			Permission: "key.read",
		},
		{
			Method: "POST", Path: "/api/v1/consumers", Handler: s.handleCreateConsumer,
			Tag: "Consumers", Summary: "Register a sink.",
			Permission: "key.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "How the sink is recognised.", Required: true},
				{Name: "kind", Type: "string", Description: "file_drop, webhook, vault_kv, kubernetes_secret, or env_export.", Required: true},
				{Name: "key_id", Type: "string", Description: "Key whose private half is delivered.", Required: true},
				{Name: "config", Type: "object", Description: "Sink-specific settings."},
				{Name: "enabled", Type: "boolean", Description: "Whether rotations deliver to it."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/consumers/{id}/deliver", Handler: s.handleDeliverConsumer,
			Tag: "Consumers", Summary: "Deliver the current private key now.",
			Permission: "key.write",
		},
		{
			Method: "DELETE", Path: "/api/v1/consumers/{id}", Handler: s.handleDeleteConsumer,
			Tag: "Consumers", Summary: "Delete a sink.",
			Permission: "key.write",
		},
		{
			Method: "GET", Path: "/api/v1/webhooks", Handler: s.handleListWebhooks,
			Tag: "Events", Summary: "List webhook subscriptions.",
			Permission: "webhook.read",
		},
		{
			Method: "POST", Path: "/api/v1/webhooks", Handler: s.handleCreateWebhook,
			Tag: "Events", Summary: "Subscribe to events.",
			Detail:     "Deliveries are signed: X-SKM-Signature carries sha256=<hex> over timestamp + \".\" + body, with the timestamp in X-SKM-Timestamp. Verify both, and reject an old timestamp, or a captured delivery can be replayed at you.",
			Permission: "webhook.write",
			Body: []Field{
				{Name: "name", Type: "string", Description: "How the subscription is recognised.", Required: true},
				{Name: "url", Type: "string", Description: "Destination. https unless the install explicitly allows otherwise.", Required: true},
				{Name: "events", Type: "string[]", Description: "Event types to receive. Empty means all of them."},
				{Name: "headers", Type: "object", Description: "Extra headers sent with every delivery, for gateway tokens and the like."},
				{Name: "secret", Type: "string", Description: "Signing secret. Generated if omitted."},
				{Name: "enabled", Type: "boolean", Description: "Whether deliveries are attempted."},
			},
		},
		{
			Method: "PATCH", Path: "/api/v1/webhooks/{id}", Handler: s.handleUpdateWebhook,
			Tag: "Events", Summary: "Enable or disable a subscription.",
			Permission: "webhook.write",
			Body: []Field{
				{Name: "enabled", Type: "boolean", Description: "Whether deliveries are attempted.", Required: true},
			},
		},
		{
			Method: "DELETE", Path: "/api/v1/webhooks/{id}", Handler: s.handleDeleteWebhook,
			Tag: "Events", Summary: "Delete a subscription.",
			Permission: "webhook.write",
		},
		{
			Method: "GET", Path: "/api/v1/webhooks/deliveries", Handler: s.handleListDeliveries,
			Tag: "Events", Summary: "Delivery attempts and their outcomes.",
			Permission: "webhook.read",
			Query: []Param{
				{Name: "webhook_id", Type: "string", Description: "Filter to one subscription."},
				{Name: "limit", Type: "integer", Description: "Page size."},
			},
		},
		{
			Method: "POST", Path: "/api/v1/webhooks/deliveries/{id}/replay", Handler: s.handleReplayDelivery,
			Tag: "Events", Summary: "Queue a delivery to be sent again.",
			Permission: "webhook.write",
		},
		{
			Method: "GET", Path: "/api/v1/events/types", Handler: s.handleListEventTypes,
			Tag: "Events", Summary: "Every event type this build emits.",
			Detail:     "Generated from the same list the emitters use, so it cannot advertise an event nothing sends.",
			Permission: "webhook.read",
		},
		{
			Method: "GET", Path: "/api/v1/events/stream", Handler: s.handleEventStream,
			Tag: "Events", Summary: "Server-sent event stream of live activity.",
			Detail:     "The bus is bounded and lossy by design: a browser that stops reading drops events rather than stalling the rotation producing them. Reconcile from the REST endpoints after a gap.",
			Permission: "job.read",
		},
		{
			Method: "GET", Path: "/api/v1/inventory/ansible", Handler: s.handleAnsibleInventory,
			Tag: "Integrations", Summary: "Dynamic inventory in Ansible's JSON format.",
			Permission: "target.read",
			Query: []Param{
				{Name: "tag", Type: "string", Description: "Restrict to targets carrying a tag.", Repeatable: true},
			},
		},
		{
			Method: "GET", Path: "/api/v1/inventory/nornir", Handler: s.handleNornirInventory,
			Tag: "Integrations", Summary: "Hosts and groups in Nornir's format.",
			Permission: "target.read",
			Query: []Param{
				{Name: "tag", Type: "string", Description: "Restrict to targets carrying a tag.", Repeatable: true},
			},
		},
		{
			Method: "GET", Path: "/api/v1/audit", Handler: s.handleListAudit,
			Tag: "Audit", Summary: "Read the audit log.",
			Permission: "audit.read",
			Query: []Param{
				{Name: "action", Type: "string", Description: "Filter by action.", Repeatable: true},
				{Name: "actor", Type: "string", Description: "Filter by actor name."},
				{Name: "resource_type", Type: "string", Description: "Filter by resource type.", Repeatable: true},
				{Name: "outcome", Type: "string", Description: "success or failure.", Repeatable: true},
				{Name: "since", Type: "string", Description: "RFC 3339 lower bound."},
				{Name: "limit", Type: "integer", Description: "Page size."},
			},
		},
		{
			Method: "GET", Path: "/api/v1/audit/verify", Handler: s.handleVerifyAudit,
			Tag: "Audit", Summary: "Walk the hash chain and report tampering.",
			Detail:     "Each row carries the hash of the one before it, so an altered or removed row breaks the chain at a nameable sequence number.",
			Permission: "audit.verify",
		},
		{
			Method: "GET", Path: "/api/v1/vault/status", Handler: s.handleVaultStatus,
			Tag: "Vault", Summary: "Seal state and key-encryption key version.",
			Permission: "vault.status",
		},
		{
			Method: "POST", Path: "/api/v1/vault/rotate-kek", Handler: s.handleRotateKEK,
			Tag: "Vault", Summary: "Rewrap every data key under a new master key.",
			Detail:     "Ciphertexts are untouched; only the wrapped data keys change. That is the point of envelope encryption: the master key can rotate without rewriting every private key.",
			Permission: "vault.rotate_kek",
			StepUp:     true,
		},
	}
}
