package qr

// Reed-Solomon error correction over GF(256).
//
// The field is generated by the primitive polynomial x^8 + x^4 + x^3 + x^2 + 1
// (0x11D) with 2 as the generator, which is what the QR specification fixes.
// Multiplication is done through log/antilog tables because a codeword's
// remainder is computed one byte at a time and table lookups keep that loop
// honest.

var (
	gfExp [512]byte // antilog, doubled so exp[a+b] needs no modulo
	gfLog [256]byte
)

func init() {
	x := 1
	for i := 0; i < 255; i++ {
		gfExp[i] = byte(x)
		gfLog[x] = byte(i)
		x <<= 1
		if x&0x100 != 0 {
			x ^= 0x11D
		}
	}
	for i := 255; i < 512; i++ {
		gfExp[i] = gfExp[i-255]
	}
}

func gfMul(a, b byte) byte {
	if a == 0 || b == 0 {
		return 0
	}
	return gfExp[int(gfLog[a])+int(gfLog[b])]
}

// generatorPoly returns the degree-n generator polynomial, coefficients
// highest-order first, as the product of (x - 2^i) for i in [0, n).
func generatorPoly(n int) []byte {
	poly := []byte{1}
	for i := 0; i < n; i++ {
		next := make([]byte, len(poly)+1)
		for j, c := range poly {
			next[j] ^= c
			next[j+1] ^= gfMul(c, gfExp[i])
		}
		poly = next
	}
	return poly
}

// reedSolomon returns the n error-correction codewords for data.
func reedSolomon(data []byte, n int) []byte {
	gen := generatorPoly(n)

	// Long division of data*x^n by gen; the remainder is the EC block.
	remainder := make([]byte, len(data)+n)
	copy(remainder, data)

	for i := 0; i < len(data); i++ {
		factor := remainder[i]
		if factor == 0 {
			continue
		}
		for j, g := range gen {
			remainder[i+j] ^= gfMul(g, factor)
		}
	}
	return remainder[len(data):]
}

// bch computes the error-correction bits used by the format and version
// information fields: the remainder of value*x^(deg) modulo the generator.
func bch(value, generator, degree int) int {
	rem := value << uint(degree)
	genBits := bitLength(generator)
	for bitLength(rem) >= genBits {
		rem ^= generator << uint(bitLength(rem)-genBits)
	}
	return value<<uint(degree) | rem
}

func bitLength(v int) int {
	n := 0
	for v != 0 {
		n++
		v >>= 1
	}
	return n
}

// formatInfo is the 15-bit format field: two bits of EC level, three of mask,
// ten of BCH, masked with 0x5412 so that an all-zero field is not valid.
func formatInfo(level Level, mask int) int {
	return bch(formatBits[level]<<3|mask, 0x537, 10) ^ 0x5412
}

// versionInfo is the 18-bit version field carried by version 7 and above.
func versionInfo(version int) int {
	return bch(version, 0x1F25, 12)
}
